export let itemData = [
    {title: "Algorithmically Fair?", 
        page: "Algorithmically-Fair", 
        year: 2022, 
        src: "/assets/portfolio/algorithmically-fair/image1.jpg", 
        alt: "Three dimensional data visualization comparing black recidivism rates to white recidivism rates", 
        tags: ["#adobe-illustrator", "#acrylic", "#public-policy", "#data-art", "#data-physicalization", "#data-visualization", "#r", "#iiba-longlist-2023"],
        tools: ["Adobe Illustrator", "R"],
        role: ["Data visualization designer", "Data analyst"],
        brief: "",
        data: "",
        sketches: []},
    {title: "Banca Intesa Knowledge Network", 
        page: "Banca Intesa Knowledge Network", 
        year: 2022, 
        src: "/assets/portfolio/banca-intesa-knowledge-network/analyze-by-area-domain-gender.png", 
        alt: "Image of network analysis across a knowledge network by area, domain, and gender", 
        tags: ["#d3-js", "#pixi-js", "#react", "#data-visualization", "#interaction-design", "#python", "#iiba-longlist-2022"],
        tools: ["D3.js", "Pixi.js", "React", "Python"],
        role: ["data visualization designer", "data analyst"],
        brief: "",
        data: "",
        sketches: []},
    {title: "Billy", 
        page: "Billy", 
        year: 2022, 
        src: "/assets/portfolio/billy/Images/HiFi-V2/Login (1).jpg",
        alt:"Image of login page for digitial wallet called Billy", 
        tags: ["#interaction-design", "#user-interface", "#figma", "#user-experience", "#user-interaction"],
        tools: ["Figma"],
        role: ["interaction designer"],
        brief: "",
        data: "",
        sketches: []},
    {title: "Black Data", 
        page: "Black-Data", 
        year: 2020, 
        src: "/assets/portfolio/black-data/20201122_142250.jpg", 
        alt:"Black cube with machine learning knitting pattern in rainbow yarn", 
        tags: ["#data-art", "#data-physicalization", "#ceramics", "#fiber", "#fine-art"],
        tools: [],
        role: ["designer"],
        brief: "",
        data: "",
        sketches: []},
    {title: "Banca Intesa Processes", 
        page: "Banca-Intesa-Processes", 
        year: "2023", 
        src: "/assets/portfolio/banca-intesa-processes/circle-packing-full-screen.png", 
        alt: "A data visualization showing multiple levels of organizational hierarchy.", 
        tags: ["#d3-js", "#pixi-js", "#react", "#data-visualization", "#interaction-design", "#python", "#iiba-longlist-2023"],
        tools: ["D3.js", "Pixi.js", "React", "Python"],
        role: ["Data visualization designer", "Project manager", "Data analyst"],
        brief: "",
        data: "",
        sketches: []},
    {title: "Meta", 
        year: 2015, 
        page: "Meta", 
        src: "/assets/portfolio/meta/keyboardhands3_slow.gif", 
        alt: "Typing out code with pink fingers", 
        tags: ["#data-art", "#data-visualization", "#r"],
        tools: ["R"],
        role: ["Designer"],
        brief: "",
        data: "",
        sketches: []},
    {title: "Visualizing Version Control", 
        page: "Visual-Version-Control", 
        year: 2021, 
        src: "/assets/portfolio/visual-version-control/version-control-system.jpg", 
        alt:"Visualizing Version Control", 
        tags: ["#graphic-design", "#information-design", "#system-design", "#adobe-illustrator"],
        tools: ["Adobe Illustrator"],
        role: ["Information designer"],
        brief: "",
        data: "",
        sketches: []},
    {title: "Drawings Collection", 
        page: "Drawings-Collection", 
        year: 2014, 
        src: "/assets/portfolio/drawings/figure/20201115_164033.jpg", 
        alt:"Sleeping person in conte.", 
        tags: ["#collection", "#charcoal", "#conte", "#drawing", "#fine-art"],
        tools: [],
        role: ["Designer"],
        brief: "",
        data: "",
        sketches: []},
    {title: "Bloom", 
        page: "Bloom", 
        year: 2022, 
        src: "/assets/portfolio/bloom/bloom-zoomed.png", 
        alt: "GIF showing the sequences of cherry blosssom blooms over time", 
        tags: ["#d3-js", "#adobe-illustrator", "#graphic-design", "#r"],
        tools: ["d3-js", "R"],
        role: ["Data visualization designer"],
        brief: "",
        data: "",
        sketches: []},
    {title: "Risky Code", 
        page: "Risky-Code", 
        year: 2023, 
        src: "/assets/portfolio/risky-code/process/ErrorRates2.png", 
        alt: "Data visualization show different recidivism rates between Black and White defendants", 
        tags: ["#information-design", "#interaction-design", "#d3-js", "#user-experience", "#data-visualization", "#react", "#r"],
        tools: ["D3.js", "React", "R"],
        role: ["Data visualization designer", "Researcher"],
        brief: "",
        data: "",
        sketches: []},
    {title: "Equitable Teams", 
        page: "Equitable-Teams", 
        year: 2022, 
        src: "assets/portfolio/equitable-teams/team_strengths_zoom.svg", 
        alt: "Data Visualization showing the combined strengths of individuals", 
        tags: ["#information-design", "#graphic-design", "#data-visualization", "#adobe-illustrator"],
        tools: ["Adobe Illustrator"],
        role: ["Data visualization designer"],
        brief: "Brainstorm the information about your peer's skills and preferences you would need to compose equitable teams. Collect data from the class. Format these requirements as a data schema, including variable names, data types, and validation. Working in pairs, use visualization to propose equitable committee membership. Create a visualization to argue for a set of teams that balance skills and preferences.",
        data: "",
        sketches: []
    },
    {title: "Ceramics Collection", 
        page: "Ceramics-Collection", 
        year: 2020, 
        src: "/assets/portfolio/ceramics/20201028_074420.jpg", 
        alt: "Serving bowl in Spodumene and Turner White", 
        tags: ["#ceramics", "#collection", "#fine-art"],
        tools: [],
        role: ["Designer"],
        brief: "",
        sketches: []
    },
    {title: "Migration is Natural", 
        page: "Migration-is-Natural",
        year: 2022, 
        src: "/assets/portfolio/migration-is-natural/path-to-citizenship-papua.jpg",
        alt:"Migration is Natural", 
        tags: ["#information-design", "#interaction-design", "#r", "#graphic-design", "#adobe-illustrator", "#d3-js", "#svelte", "#figma"],
        tools: ["R", "Adobe Illustrator", "D3.js", "Svelte", "Figma"],
        role: ["Data visualization designer", "Project manager", "Data analyst"],
        brief: "Using data from the global citizenship database create a task-based visualization that explores the dataset. Create an interactive interface that features three information visualizations. The visualizations should balance the database's complexity with a goal of user-friendliness.",
        data: "This project combines data from two resources. The first is the global citizenship database maintained by the European University Institute. The database standardizes citizenship acquisition methods across 190 countries. The database identifies 28 ways through which migrants can obtain citizenship. It was last updated on January 1st, 2020. This data set was challenging to work with because the data are all categorical, which is often harder to visualize than numeric data.",
        sketches: []
    },
    {title: "Public Policy Collection", 
        page: "Public-Policy-Collection", 
        year: 2020, 
        src: "/assets/portfolio/public-policy-collection/harris county child care markets simple.PNG", 
        alt:"Map of Harris County, Texas child care deserts", 
        tags: ["#data-visualization", "#interaction-design", "#r", "#public-policy", "#collection"],
        tools: ["R"],
        role: ["Data visualization designer", "Project manager", "Data analyst"],
        brief: "Design an interactive visualization that shows child care deserts by census tract in Tarrant and Harris Country, Texas. Users should be able to visually assess geographic areas with a low supply of childcare compared to the demand for childcare. The target audience for this application is policy researchers.",
        data: "This dashboard combines data from various sources, including the Texas Child Care Licensing database, Texas Workforce Commission, and the Census.",
        sketches: []
    },
    {title: "Tutor Match", 
        page: "Tutor-Match", 
        year: 2022, 
        src: "/assets/portfolio/tutor-match/Images/Wireframe/20221213/Main2.jpg", 
        alt:"Image of user interface design for homescreen of tutor match", 
        tags: ["#interaction-design", "#user-interface", "#figma", "#user-experience", "#user-interaction"],
        tags: ["Figma"],
        role: ["Interaction designer"],
        brief: "",
        data: "",
        sketches: []
    },
    {title: "Patient Clinician Interactions", 
        page: "Patient-Clinician-Interactions", 
        year: 2022, 
        src: "/assets/portfolio/healthcare-patient-clinician-interaction/system-zoomed.jpg", 
        alt:"Image healthcare system clincian-patient hypothesized interactions", 
        tags: ["#service-design", "#system-design", "#graphic-design", "#adobe-illustrator"],
        tools: ["Adobe Illustrator"],
        role: ["Information designer", "Researcher"],
        brief: "",
        data: "",
        sketches: []
    }
    //     ,{title: "Flee", 
    //     page: "Flee", 
    //     year: 2022, 
    //     src: "/assets/portfolio/flee/", 
    //     tags: ['#data-journalism', '#react', '#r', '#figma', '#adobe-illustrator', '#d3-js'],
    //     tools: ["R", "Adobe Illustrator", "D3.js"],
    //     role: ["Data Visualization Designer"],
    //     brief: "",
    //     data: "",
    //     sketches: []
    // }
];

export const designFilters = [
"#data-physicalization", "#data-visualization", "#information-design",
"#interaction-design", "#graphic-design", "#system-design", "#service-design", "#user-experience", "#user-interaction" ];

export const mediumFilters = ["#acrylic", "#ceramics", "#charcoal", "#conte", "#fiber"];

export const toolFilters = ["#adobe-illustrator", "#d3-js", "#figma", "#python", "#r", "#react"];

export const areaFilters = ["#data-art", "#data-journalism", "#fine-art", "#map", "#public-policy" ];

export const awardFilters = ["#iiba-longlist-2023", "#iiba-longlist-2022"]

export const filters = awardFilters.concat(toolFilters.concat(designFilters.concat(mediumFilters)));
